/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Java_MySQL_CRUD_operations;


import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Java_CRUD extends javax.swing.JFrame {
    
    
    private static final String username = "root";
    private static final String password = "";
    private static final String database_connector = "jdbc:mysql://localhost:3306/soldiers_database?zeroDateTimeBehavior=CONVERT_TO_NULL";
    
    // Connecting Db to Java
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q, i, id, deleteItem;
    
    
    

    /**
     * Creates new form NewJFrame
     */
    public Java_CRUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws java.sql.SQLException
     */
    
    //===============================Function================================
    public void upDateDATABASE() throws SQLException
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(database_connector, username, password);
            pst = sqlConn.prepareStatement("SELECT * FROM biography_information");
            rs = pst.executeQuery();

            ResultSetMetaData stData = rs.getMetaData();
            q = stData.getColumnCount();

            DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
            RecordTable.setRowCount(0);

    while (rs.next()) {
        Vector<Object> columnData = new Vector<>();
        columnData.add(rs.getInt("ID"));
        columnData.add(rs.getString("Surname"));
        columnData.add(rs.getString("Forename"));
        columnData.add(rs.getString("Service_Number"));
        columnData.add(rs.getString("Regiment"));
        columnData.add(rs.getString("Biography"));
        RecordTable.addRow(columnData);
        }
    } catch (ClassNotFoundException | SQLException ex) {
        JOptionPane.showMessageDialog(null, ex);
        Logger.getLogger(Java_CRUD.class.getName()).log(Level.SEVERE, null, ex);
    } finally {
        try {
            if (rs != null) rs.close();
            if (pst != null) pst.close();
            if (sqlConn != null) sqlConn.close();
    } catch (SQLException ex) {
            Logger.getLogger(Java_CRUD.class.getName()).log(Level.SEVERE, null, ex);
    }
}

    }
    
    
    
    
    //===============================END FUNCTION============================
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtSurname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtForename = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtServiceNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtRegiment = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtBiography = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtxtID = new javax.swing.JTextField();
        btnID = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnUpdateData = new javax.swing.JButton();
        btnAddNewData = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Surname");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 30));

        jtxtSurname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 640, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Forename");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        jtxtForename.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(jtxtForename, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 640, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Service No");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 70, 30));

        jtxtServiceNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(jtxtServiceNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 640, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Regiment");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, 30));

        jtxtRegiment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(jtxtRegiment, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 640, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Biography");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 70, 30));

        jtxtBiography.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(jtxtBiography, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 640, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Surname", "Forename", "Service No", "Title 5", "Biography"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 730, 90));

        jtxtID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel2.add(jtxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 640, -1));

        btnID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnID.setText("ID");
        jPanel2.add(btnID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 810, 290));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUpdateData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateData.setText("Update Data");
        jPanel3.add(btnUpdateData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, 20));

        btnAddNewData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddNewData.setText("Add New Data");
        btnAddNewData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewDataActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddNewData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 120, 20));

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel3.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, 20));

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPrint.setText("Print");
        jPanel3.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 20));

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel3.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, 120, 20));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        jPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 120, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 140, 290));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("MySQL Connector");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 70));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 960, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1030, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private JFrame frame;
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "MySQL Connector",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) 
        {
            System.exit(0);
            
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        jtxtID.setText("");
        jtxtSurname.setText("");
        jtxtForename.setText("");
        jtxtServiceNo.setText("");
        jtxtRegiment.setText("");
        jtxtBiography.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddNewDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewDataActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            sqlConn = DriverManager.getConnection(database_connector, username, password);
            pst = sqlConn.prepareStatement("INSERT into biography_information(ID,Surname,Forename,Service_Number," +"Regiment,Biography)value(?,?,?,?,?,?)");
            
            pst.setString(1, jtxtID.getText());
            pst.setString(2, jtxtSurname.getText());
            pst.setString(3, jtxtForename.getText());
            pst.setString(4, jtxtServiceNo.getText());
            pst.setString(5, jtxtRegiment.getText());
            pst.setString(6, jtxtBiography.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");
            upDateDATABASE();
        } 
        catch(ClassNotFoundException ex) 
        {
            java.util.logging.Logger.getLogger(Java_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        catch (SQLException ex)
        {
            java.util.logging.Logger.getLogger(Java_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddNewDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Java_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Java_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Java_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Java_CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Java_CRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewData;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel btnID;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdateData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxtBiography;
    private javax.swing.JTextField jtxtForename;
    private javax.swing.JTextField jtxtID;
    private javax.swing.JTextField jtxtRegiment;
    private javax.swing.JTextField jtxtServiceNo;
    private javax.swing.JTextField jtxtSurname;
    // End of variables declaration//GEN-END:variables
}
