package com.example.lockdownfeature.demo;

public class Soldier {
    private int id;
    private String surname;
    private String forename;
    private String regiment;
    private String cemetery;

    // Getters and setters
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getForename() {
        return forename;
    }

    public void setForename(String forename) {
        this.forename = forename;
    }

    public String getRegiment() {
        return regiment;
    }

    public void setRegiment(String regiment) {
        this.regiment = regiment;
    }

    public String getCemetery() {
        return cemetery;
    }

    public void setCemetery(String cemetery) {
        this.cemetery = cemetery;
    }
}
